### ISSUE TITLE
Loader replaces only first entry of the pattern in each file.

### ISSUE THREAD

**Issue by SergeyDubinets** [aganglada/pattern-replace-loader#7]
If you use string as a pattern (not a RegEx) replace() method replaces only first entry of the given pattern in each files.

I don't think this is by design.

**Comment by aganglada** [comment]
Hey @SergeyDubinets thanks for bringing this up.

You have the option of passing `options.flags` as `g` (global), then it will do what you expect.

Hope it helps :)
